### PR TITLE
Update docs to include singularity container

### PR DESCRIPTION
**Pull request by jsmentch**
as requested in #1 adds info on how to run dyneusr with a prebuilt singularity container hosted on singularity-hub

### CODE REVIEW

**Comment by calebgeniesse** [comment]
if you don't mind, let's also include the following changes here
- [ ] add singularity recipe from singularity-hub
- [ ] link to the container in [`README.md`](https://github.com/braindynamicslab/dyneusr/blob/master/README.md) (see badge/code below)

**Comment by calebgeniesse** [comment]
**badge**

[](https://singularity-hub.org/collections/4218) 

**code**

```
[![https://www.singularity-hub.org/static/img/hosted-singularity--hub-%23e32929.svg](https://www.singularity-hub.org/static/img/hosted-singularity--hub-%23e32929.svg)](https://singularity-hub.org/collections/4218)
```

**Comment by jsmentch** [comment]
Ok I think I made those changes. I just added the recipe file to the main directory since there is only one but if there are more in the future and different versions, might be good to make a containers subfolder

**Comment by calebgeniesse** [comment]
awesome, thanks!

**Comment by calebgeniesse** [comment]
merging now ... this should trigger an automated build on [singularity-hub](https://singularity-hub.org/collections/4218)

thanks again, @jsmentch!

**Comment by jsmentch** [comment]
You're welcome, yup looks like it built successfully! just tried it out on the cluster here and could import dyneusr using that image without any errors

**Pull request merged**
